version: '3.8'
services:
  geonovation.web:
    image: nginx:latest
    ports:
      - 6000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - drupal
  drupal:
    image: drupal:7.99-php8.2-fpm-bullseye
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=geonovation_website
      - MYSQL_USER=geonovation
      - MYSQL_PASSWORD=6#aS7#muTvSJo
    depends_on:
        - mysql
  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=geonovation_website
      - MYSQL_USER=geonovation
      - MYSQL_PASSWORD=Q2r#22XRQYPe9@
      - MYSQL_ROOT_PASSWORD=eLLfLLrN#Q87Us
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 81:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=eLLfLLrN#Q87Us
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
volumes:
  mysql:
    name: geonovation_drupal_mysql