version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      # - ./ssl-certificates/YOURWEBSITE.org:/etc/letsencrypt/live/YOURWEBSITE.org:ro
      # - ./ssl-certificates/www.YOURWEBSITE.org:/etc/letsencrypt/live/www.YOURWEBSITE.org:ro
    depends_on:
      - drupal
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./nginx/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log
    depends_on:
        - mysql
    command: "sh scripts/start.sh"
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=website_database
      - MYSQL_USER=website_user
      - MYSQL_PASSWORD=website_password
      - MYSQL_ROOT_PASSWORD=website_root_password
    volumes:
      - mysql:/var/lib/mysql
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - 81:80
#    environment:
#      - PMA_HOST=mysql
#      - PMA_USER=root
#      - PMA_PASSWORD=website_root_password
#      - PMA_ARBITRARY=1
#    depends_on:
#      - mysql
volumes:
  mysql:
    name: drupal_mysql